---

  - name: Copy-files
    hosts: linux_nodes
    become: true

<<<<<<< HEAD
     tasks:   
=======
    tasks:
>>>>>>> c3ef6ef52ff426223cd9c288d64751b0dbb71cdd
      - name: Copy RedHat files
        copy: 
          src: "{{ item.src }}"
          dest: "{{ item.src }}"
        loop:
          - { src: 'redhat-files/rfile1.txt', dest: '/etc/myfolder/'} 
          - { src: 'redhat-files/rfile2.txt', dest: '/etc/myfolder/'} 
        when: ansible_os_family == 'RedHat'

      - name: Copy Debian files
        copy: 
          src: "{{ item.src }}"
          dest: "{{ item.src }}"
        loop:
          - { src: 'debian-files/dfile1.txt', dest: '/etc/myfolder/'} 
          - { src: 'debian-files/dfile2.txt', dest: '/etc/myfolder/'} 
        when: ansible_os_family == 'Debian'
          
