---

- name: Strategies example
  hosts: linux_nodes
  become: yes 
  gather_facts: no 
<<<<<<< HEAD
  serial: 2
=======
  serial: 1
  
>>>>>>> 5dffc0315373c2302193ffb3ad7511b6e640564e

  tasks:

    - name: Ping targets
      ping: 

    - name: Sleep for 3 seconds
      shell: "sleep 3" 

    - name: Uptime
      command: "uptime"
      register: result


    - name: Print uptime information 
      debug: 
        var: result.stdout
