    - name: Copy RedHat files
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: 'redhat-files/rfile1.txt', dest: '/etc/myfolder/'} 
        - { src: 'redhat-files/rfile2.txt', dest: '/etc/myfolder/'} 
      notify: 
        - RedHat files copied
      when: ansible_os_family == 'RedHat'